# Generated by Django 4.1.6 on 2023-03-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='biometric_details',
            field=models.ImageField(null=True, upload_to='biometric_details'),
        ),
    ]
