# Generated by Django 4.1.6 on 2023-03-06 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60)),
                ('logo_Image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='product added at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=70)),
                ('lname', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER')], default='MALE', max_length=20)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Is_Checked', models.BooleanField(default=False)),
                ('Is_approved', models.BooleanField(default=False)),
                ('aadhar_no', models.IntegerField(default='0')),
                ('front_img', models.ImageField(blank=True, upload_to='adhar_front')),
                ('back_img', models.ImageField(blank=True, upload_to='adhar_back')),
                ('pan_no', models.CharField(blank=True, max_length=70)),
                ('pan_img', models.ImageField(blank=True, upload_to='pan_img')),
                ('voter_id', models.CharField(blank=True, max_length=70)),
                ('voter_img', models.ImageField(blank=True, upload_to='voter_img')),
                ('transaction_id', models.CharField(blank=True, default=uuid.UUID('db139562-154b-4085-82a1-36dc245b56dd'), max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
