# Generated by Django 4.1.6 on 2023-03-06 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('8c76f945-e7f2-49bf-922e-5ac514418d20'), max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
