# Generated by Django 4.1.6 on 2023-03-06 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_transaction_id_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('b11da410-b3a5-4619-99a4-5b0c4b6a41b2'), max_length=100, null=True, unique=True),
        ),
    ]
