# Generated by Django 4.1.6 on 2023-03-06 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('3116253b-bc63-4c81-8bb2-c91b8f243800'), max_length=100, null=True, unique=True),
        ),
    ]
