# Generated by Django 4.1.6 on 2023-03-06 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('c2fdea2a-0af4-46ae-8527-9ea9050e0202'), max_length=100, null=True, unique=True),
        ),
    ]
