# Generated by Django 4.1.6 on 2023-03-07 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('67b8eb33-f1a1-4e41-afd5-a5ab9d6a759b'), max_length=100, null=True, unique=True),
        ),
    ]
