# Generated by Django 4.1.6 on 2023-03-13 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('95a94e12-8562-4222-b3f1-fcf20cb59973'), max_length=100, null=True, unique=True),
        ),
    ]
