# Generated by Django 4.1.6 on 2023-03-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_rename_user_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('d7a8d768-862f-40f0-a5cc-4610f0d5ef71'), max_length=100, null=True, unique=True),
        ),
    ]
